[package]
name = "chip-8"
version = "0.1.0"
authors = ["b0ney <40839054+B0ney@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.3"
rand = "0.8.3"